<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FocusLock.Service</AssemblyName>
    <Version>7.7.9</Version>
    <AssemblyVersion>7.7.9.0</AssemblyVersion>
    <FileVersion>7.7.9.0</FileVersion>
    <InformationalVersion>7.7.9</InformationalVersion>
    <RootNamespace>FocusLock.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FocusLock.Shared\FocusLock.Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
  </ItemGroup>
</Project>
